sudo: required
language: node_js
node_js:
  - "4"

services:
  - docker

install:
  - docker --version
  - docker-compose --version
  - docker-compose -f docker-compose-ci.yml build
  - docker-compose -f docker-compose-ci.yml up -d

before_script:
  - npm install -g newman

script:
  - ./run-integration-tests.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag choefele/swift-server-app choefele/swift-server-app:${TRAVIS_COMMIT::8}-$TRAVIS_BUILD_NUMBER;
    docker push choefele/swift-server-app;
    fi