version: '2'
services:
  db:
    image: mongo:3.2.9
  data:
    image: alpine
    volumes:
      - datavolume:/data/db
    command: echo Data container
  app:
    build: .
    ports:
      - "8090:8090"