version: '2'
services:
  db:
    image: mongo:3.2.9
  data:
    image: alpine:3.4
    volumes:
      - datavolume:/data/db
    command: echo Data container
  app:
    image: choefele/swift-server-app
    ports:
      - "8090:8090"