version: '2'
services:
  db:
    ports:
      - "27017:27017"
    extends:
      file: docker-compose-common.yml
      service: db
    volumes_from:
      - data
  data:
    extends:
      file: docker-compose-common.yml
      service: data
volumes:
  datavolume: