version: '2'
services:
  db:
    extends:
      file: docker-compose-common.yml
      service: db
  app:
    environment:
      - DB_URL = mongodb://db
    depends_on:
      - db
    extends:
      file: docker-compose-common.yml
      service: app
